### ISSUE TITLE
System.InvalidOperationException: A valid active Window is needed to update the Taskbar

### ISSUE THREAD

**Issue by MagicAndre1981** [pierresprim/Windows-API-Code-Pack#11]
I found a regression between Previe2 and Preview3. 

This code (which worked since old Microsoft implementation until Preview2):

            if (TaskbarManager.IsPlatformSupported)
            {
                TaskbarManager.Instance.SetProgressState(TaskbarProgressBarState.NoProgress);
            }

I now get a System.InvalidOperationException:

```
************** Ausnahmetext **************
System.InvalidOperationException: A valid active Window is needed to update the Taskbar.
   bei Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.get_OwnerHandle()
   bei Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.SetProgressState(TaskbarProgressBarState state)
   bei FooApp.frmBar_FormClosed(Object sender, FormClosedEventArgs e)
```
When I close a Window which changed progressbar I would like to reset it and this code always worked until now at your Preview 3.

VS2017 15.9.x
WinForms: .Net 4.8 + Windows-API-Code-Pack v2.0.0-preview3

**Comment by MagicAndre1981** [comment]
I also tried to move it from [FormClosed](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.formclosed?view=netframework-4.8) to [FormClosing](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.formclosing?view=netframework-4.8) Event, still the same error message all time.

**Comment by pierresprim** [comment]
I fixed the bug, I'll upload the new version of the nuget packages as soon as possible. Thank you for pointing it out.

**Comment by MagicAndre1981** [comment]
thanks, preview6 works for me.
