### ISSUE TITLE
An Error:Unable to cast COM object of type 'System.__ComObject' to interface type 'Shell32.Shell'

### ISSUE THREAD

**Issue by kingxi82** [pierresprim/Windows-API-Code-Pack#20]
When I develope a WPF Project With Windows-API-Code-Pack on Windows 10 by VS2019,I visit a smb directory. it works on Windows 10 and windows 8, but it throw a exception on windows 7 like this:
Unable to cast COM object of type 'System.__ComObject' to interface type 'Shell32.Shell'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))

I found some references,but i don't known how to solve this problem with Windows-API-Code-Pack
https://social.msdn.microsoft.com/Forums/vstudio/en-US/b25e2b8f-141a-4a1c-a73c-1cb92f953b2b/instantiate-shell32shell-object-in-windows-8?forum=clr

**Comment by pierresprim** [comment]
@kingxi82 There is no namespace Shell32 in the Windows API Code Pack because the COM interfaces are implemented without referencing shell32.dll in the project file, so I do not know what you mean. Could you provide more details about your issue? What class/interface are you calling?

**Comment by kingxi82** [comment]
There's no fault in the Windows API Code Pack.  I'm being too careless; Thank you for your reply.I used Shell32.shell to set disk drive's VolumeLabel before call the api of Windows API Code Pack.
