### ISSUE TITLE
Please support net framework 3.5 or 4.5

### ISSUE THREAD

**Issue by IOL0ol1** [pierresprim/Windows-API-Code-Pack#22]
Older projects should provide lower net framework support.
In order to use this historic library, I actually needed to upgrade all my projects to 4.7.2, Is this necessary?

**Comment by TMS-Namespace** [comment]
I believe you can change the supported framework manually in the source code,  A fast glance didn't show me that they are using framework specific features (except shared projects that can be fxed manually).
